spring.application.name=sb-ecommercee

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


#Database JDBC URL [jdbc:h2:mem:b240e024-c88f-4105-9938-baa23cb1982f]
